export enum ProxyTagType {
  BRAND = 'BRAND',
  OPTION_NAME = 'OPTION_NAME',
  OPTION_VALUE = 'OPTION_VALUE',
  MIDDLE_PROXY_SHOPPING_CATEGORY = 'MIDDLE_PROXY_SHOPPING_CATEGORY',
  MAIN_PROXY_SHOPPING_CATEGORY = 'MAIN_PROXY_SHOPPING_CATEGORY',
}
